DROP TABLE IF EXISTS codigo;
DROP TABLE IF EXISTS bilhete;
DROP TABLE IF EXISTS administrador;

CREATE TABLE administrador (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE bilhete (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo INTEGER NOT NULL,
  nome TEXT NOT NULL,
  sobrenome TEXT NOT NULL,
  celular TEXT NOT NULL,
  horario TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE codigo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo INTEGER NOT NULL,
  horario TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)