DROP TABLE IF EXISTS administrador;
DROP TABLE IF EXISTS bilhete;
DROP TABLE IF EXISTS codigo;
DROP TABLE IF EXISTS sorteio;

CREATE TABLE administrador (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE bilhete (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo INTEGER NOT NULL,
  nome TEXT NOT NULL,
  sobrenome TEXT NOT NULL,
  celular TEXT NOT NULL,
  horario TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_sorteio INTEGER NOT NULL,
  FOREIGN KEY (id_sorteio) REFERENCES sorteio(id)
);

CREATE TABLE codigo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo INTEGER NOT NULL,
  horario TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_sorteio INTEGER NOT NULL,
  FOREIGN KEY (id_sorteio) REFERENCES sorteio(id)
);

CREATE TABLE sorteio (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT UNIQUE NOT NULL,
  data_limite TIMESTAMP NOT NULL,
  realizado BOOLEAN DEFAULT 0,
  id_bilhete_sorteado INTEGER DEFAULT NULL,
  FOREIGN KEY (id_bilhete_sorteado) REFERENCES bilhete(id),
  CHECK ((NOT realizado) OR id_bilhete_sorteado)
);